image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - test
  - publish
  - deploy

variables:
  LATEST: $CI_REGISTRY_IMAGE:latest
  STACK_NAME: curilab

build-container:
  stage: build
  script:
    - docker build -t $LATEST .

test:
  stage: test
  script:
    - docker run --rm -d --name mongodb-test mongo:latest
    - docker run --rm --link mongodb-test:mongo -e MONGO_DB_URL=mongodb://mongo $LATEST sh -c "mvn test"
  after_script:
    - docker rm -f mongodb-test

publish-image:
  stage: publish
  only:
    - master
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker push $LATEST

deploy:
  image: $CI_REGISTRY/curilab/hermes:latest
  stage: deploy
  only:
    - master
  script:
    - kontena stack upgrade --force $STACK_NAME || kontena stack install --name $STACK_NAME
