---
stack: vngu/curilab
version: '0.0.1'
description: curilab
services:
  api:
    image: registry.gitlab.com/curilab/asclepius:latest
    instances: 1
    environment:
      - KONTENA_LB_INTERNAL_PORT=5555
      - KONTENA_LB_VIRTUAL_HOSTS=curilab-api.quving.com
      - TZ=Europe/Berlin
    links:
      - system/lb
      - db

  db:
    image: mongo:latest
    instances: 1
    affinity:
      - node==orange
    stateful: yes
    volumes:
      - /srv/curilab:/data/db
    links:
      - system/lb
    ports:
      - 27072:27017
    environment:
      - TZ=Europe/Berlin
